# Generated by Django 3.1.3 on 2023-09-08 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_source', '0004_logsource_number_log_source'),
        ('user_management', '0005_company_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField()),
                ('escalado_a', models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('interno', 'Interno'), ('infraestructura', 'Infraestructura')], max_length=50, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('name_log_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_source.logsource')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
