# Generated by Django 3.1.3 on 2023-09-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitycheckmcafee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohistorico',
            name='escalado_a',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('interno', 'Interno'), ('infraestructura', 'Infraestructura'), ('Sin Gestión', 'Sin Gestión')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
