# Generated by Django 4.1.9 on 2023-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20230118_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
