# Generated by Django 3.1.3 on 2022-12-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_source', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpsLogSource',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_epslogsource', models.AutoField(primary_key=True, serialize=False)),
                ('count_range', models.PositiveSmallIntegerField(default=0)),
                ('count_intervale', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('name_log_source', models.ForeignKey(db_column='id_name_log_source', on_delete=django.db.models.deletion.CASCADE, to='log_source.logsource')),
            ],
            options={
                'verbose_name': 'EpsLogSource',
                'verbose_name_plural': 'EpsLogSource',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='EpsManagement',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_epsmanagement', models.AutoField(primary_key=True, serialize=False)),
                ('eps_limit', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
            ],
            options={
                'verbose_name': 'EpsManagement',
                'verbose_name_plural': 'EpsManagement',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_notification', models.AutoField(primary_key=True, serialize=False)),
                ('eps_notification', models.PositiveSmallIntegerField(default=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('eps_management', models.ForeignKey(db_column='id_eps_management', on_delete=django.db.models.deletion.CASCADE, to='eps_management.epsmanagement')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notification',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='EpsTotal',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_epstotal', models.AutoField(primary_key=True, serialize=False)),
                ('count_range', models.PositiveSmallIntegerField(default=0)),
                ('count_intervale', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('eps_log_source', models.ManyToManyField(to='eps_management.EpsLogSource')),
                ('notification', models.ManyToManyField(to='eps_management.Notification')),
            ],
            options={
                'verbose_name': 'EpsTotal',
                'verbose_name_plural': 'EpsTotal',
                'ordering': ('-created_date',),
            },
        ),
    ]
