# Generated by Django 3.1.3 on 2022-12-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epslogsource',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
