# Generated by Django 3.1.3 on 2022-12-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0002_auto_20221223_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epstotal',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
