# Generated by Django 3.1.3 on 2022-12-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0003_auto_20221223_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epstotal',
            name='count_intervale',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
