# Generated by Django 3.1.3 on 2022-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0004_auto_20221226_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epslogsource',
            name='count_intervale',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epslogsource',
            name='count_range',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epsmanagement',
            name='eps_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epstotal',
            name='count_range',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='eps_notification',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
