# Generated by Django 3.1.3 on 2023-01-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_company_domain_id_qradar'),
        ('log_source', '0004_logsource_number_log_source'),
        ('eps_management', '0005_auto_20221226_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpsERCAllMcafee',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_epsercallmcafee', models.AutoField(primary_key=True, serialize=False)),
                ('erc_collection_rate', models.PositiveIntegerField(default=0)),
                ('erc_parsing_rate', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
            ],
            options={
                'verbose_name': 'EpsERCAllMcafee',
                'verbose_name_plural': 'EpsERCAllMcafee',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='EPS_DS_Parsing_Rate',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_epsdsparsingrate', models.AutoField(primary_key=True, serialize=False)),
                ('ds_parsing_rate', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('epsercallmcafee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eps_management.epsercallmcafee')),
                ('log_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_source.logsource')),
            ],
            options={
                'verbose_name': 'EPS_DS_Parsing_Rate',
                'verbose_name_plural': 'EPS_DS_Parsing_Rate',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='EPS_DS_Collection_Rate',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_epsdscollectionrate', models.AutoField(primary_key=True, serialize=False)),
                ('ds_collection_rate', models.PositiveIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('epsercallmcafee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eps_management.epsercallmcafee')),
                ('log_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_source.logsource')),
            ],
            options={
                'verbose_name': 'EPS_DS_Collection_Rate',
                'verbose_name_plural': 'EPS_DS_Collection_Rate',
                'ordering': ('-created_date',),
            },
        ),
    ]
