# Generated by Django 3.1.3 on 2023-01-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0006_eps_ds_collection_rate_eps_ds_parsing_rate_epsercallmcafee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epsercallmcafee',
            name='created_date',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
    ]
