# Generated by Django 3.1.3 on 2023-01-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0007_auto_20230117_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps_ds_collection_rate',
            name='created_date',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='eps_ds_parsing_rate',
            name='created_date',
            field=models.DateTimeField(verbose_name='Fecha de Creación'),
        ),
    ]
