# Generated by Django 3.1.3 on 2023-01-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0008_auto_20230118_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps_ds_collection_rate',
            name='epsercallmcafee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eps_ds_collection_rate_epsercallmcafee', to='eps_management.epsercallmcafee'),
        ),
        migrations.AlterField(
            model_name='eps_ds_parsing_rate',
            name='epsercallmcafee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eps_ds_parsing_rate_epsercallmcafee', to='eps_management.epsercallmcafee'),
        ),
    ]
