# Generated by Django 3.1.3 on 2023-01-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0009_auto_20230118_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='epsercallmcafee',
            name='name_file',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
