# Generated by Django 3.1.3 on 2023-01-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eps_management', '0010_epsercallmcafee_name_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='eps_ds_collection_rate',
            name='name_file',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='eps_ds_parsing_rate',
            name='name_file',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
