"""
Django settings for eps project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3jb+e8ics9usxma!b$6-$n94^^#-h(96d7s$ezn1(7b_!-g^vy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # own
    'user_management',
    'eps_management',
    'log_source',
    'query_management',
    'sanitycheckmcafee',

    # 3rd party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_crontab',
    'djoser',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'eps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

try:

    PROD = os.environ['ATN_PROD']
    API_GET_PASSWORD = '26506aee-aab1-49cf-87f9-537964033af6'
    API_URL_BASIC = 'https://172.16.133.10/api/'

    if PROD:
        DATABASES = {
            'default': {
                'ENGINE': os.environ['ATN_DB_ENGINE'],
                'NAME': os.environ['ATN_DB'],
                'USER': os.environ['ATN_DB_USER'],
                'PASSWORD': os.environ['ATN_DB_PASSWD'],
                'HOST': os.environ['ATN_DB_HOST'],
                'PORT': os.environ['ATN_DB_PORT'],
            }
        }

except Exception as E:
    raise ValueError(E)

AUTH_USER_MODEL = 'user_management.User'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Chile/Continental'

USE_TZ = True

USE_I18N = True

USE_L10N = True

USE_TZ = True

OTP_NAME = 'CyberDefense - Cybersecurity Strategies'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/code/static/'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

CRONTAB_COMMAND_SUFFIX = '2>&1'

CRONJOBS = [
    ('*/3 * * * *', 'eps_management.cronjobs.import_new_eps', '>> /home/logs/logs_eps_qradar.log'),
    ('*/10 * * * *', 'eps_management.cronjobs.import_new_eps_mcafee', '>> /home/logs/logs_eps_mcafee.log'),
    ('* * * * *', 'sanitycheckmcafee.cronjobs.import_new_sanity_trellix', '>> /home/logs/sanitytrallex.log'),
]