# Generated by Django 3.1.3 on 2023-10-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIncident',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_type_incident', models.AutoField(primary_key=True, serialize=False)),
                ('name_type_incident', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'TypeIncident',
                'verbose_name_plural': 'TypeIncident',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_incident', models.AutoField(primary_key=True, serialize=False)),
                ('name_incident', models.CharField(max_length=256)),
                ('type_incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident_handler_management.typeincident')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incident',
                'ordering': ('-created_date',),
            },
        ),
    ]
