# Generated by Django 3.1.3 on 2023-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_of_use_management', '0002_caseuse_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseuse',
            name='observation',
            field=models.TextField(default=''),
        ),
    ]
