# Generated by Django 3.1.3 on 2022-12-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_module', models.AutoField(primary_key=True, serialize=False)),
                ('name_module', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Module',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('enabled', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('id_datasource', models.AutoField(primary_key=True, serialize=False)),
                ('name_log_source', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.company')),
                ('module', models.ManyToManyField(to='log_source.Module')),
            ],
            options={
                'verbose_name': 'LogSource',
                'verbose_name_plural': 'LogSource',
                'ordering': ('-created_date',),
            },
        ),
    ]
