# Generated by Django 3.1.3 on 2022-12-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsource',
            name='module',
            field=models.ManyToManyField(blank=True, null=True, to='log_source.Module'),
        ),
    ]
