# Generated by Django 3.1.3 on 2022-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_source', '0002_auto_20221223_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsource',
            name='module',
            field=models.ManyToManyField(blank=True, to='log_source.Module'),
        ),
    ]
