# Generated by Django 3.1.3 on 2023-01-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_source', '0003_auto_20221227_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='number_log_source',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
