# Generated by Django 3.1.3 on 2023-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_source', '0004_logsource_number_log_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='estado_datasource',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logsource',
            name='ip',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='logsource',
            name='seguir_escalando',
            field=models.BooleanField(default=True),
        ),
    ]
