# Generated by Django 3.1.3 on 2023-09-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_source', '0005_auto_20230920_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='zona_horaria',
            field=models.CharField(blank=True, choices=[('UTC', 'UTC'), ('GTM-3', 'GTM-3'), ('GTM-4', 'GTM-4')], max_length=50, null=True),
        ),
    ]
