# Generated by Django 3.1.3 on 2024-05-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise_resource_planning_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/no-image.png', upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
